### ISSUE TITLE
The link to the videos showed "404"

### ISSUE THREAD

**Issue by meisa233** [Tangshitao/ClipShots#1]
Can you fix this error?
Thank you.

**Comment by Tangshitao** [comment]
We haven't released the videos currently, because it's too large. We will make it release soon. I can promise before December.

**Comment by meisa233** [comment]
> We haven't released the videos currently, because it's too large. We will make it release soon. I can promise before December.

Thanks for your response.

**Comment by Tangshitao** [comment]
We have released videos. https://pan.baidu.com/s/1J3fdQxPUtkMe6i8moCXZ0A
