### ISSUE TITLE
Hello, I changed the name of the root folder to data.tar.gz, then what? It is still a folder..., is there any tool to convert it?

### ISSUE THREAD

**Issue by DYF-AI** [Tangshitao/ClipShots#15]
Hello, I changed the name of the root folder to data.tar.gz, then what? It is still a folder..., is there any tool to convert it?
![image](https://user-images.githubusercontent.com/54470509/123187461-c9dc3180-d4cc-11eb-9e48-9e5b3f769277.png)

**Comment by Tangshitao** [comment]
Maybe cat Clipshot* > data.tar.gz. I forgot the exact commend.

**Comment by DYF-AI** [comment]
```shell
> Maybe cat Clipshot* > data.tar.gz. I forgot the exact commend.

./ClipShots/videos/train/PsywarFullDocumentarymkv.mp4

gzip: stdin: invalid compressed data--crc error

gzip: stdin: invalid compressed data--length error
tar: 归档文件中异常的 EOF
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now
```
```shell
cat ClipShots-a ClipShots-b ClipShots-c > data.tar.gz
// cat ClipShots* > data.tar.gz
tar -zxvf data.tar.gz  
// tar -xvf data.tar.gz
```
Hi, the compressed file I generated, but the above problem occurred during decompression...

**Comment by Tangshitao** [comment]
The files seem broken. Can you try to download these files again? The raw data is in the company's server and I have left  the company. I don't have the raw data right now. I'm also connecting other authors trying to restore the link of Google drive.

**Comment by Tangshitao** [comment]
Please use this link. https://drive.google.com/file/d/1Z9iTwKT07gFWLp3GTltsB71MESugguza/view?usp=sharing

**Comment by DYF-AI** [comment]
> Please use this link. https://drive.google.com/file/d/1Z9iTwKT07gFWLp3GTltsB71MESugguza/view?usp=sharing

Thank you for your reply, I have used cosine similarity to find the video shot, so this data set should not be needed for the time being, thanks
