### ISSUE TITLE
Could you afford the prtrained model and inference code for evaluation

### ISSUE THREAD

**Issue by zzc-master** [Tangshitao/ClipShots#2]
Hi,
I am very interested in your work for the contribution of dataset and novel method.  I am going to do some work upon on your work, Could you afford the pre-trained model and inference code for evaluation for convenient comparison?

Thanks!

**Comment by Tangshitao** [comment]
Sorry for late response. Please refer to https://github.com/Tangshitao/ClipShots_basline

**Comment by vBLFTePebWNi6c** [comment]
Hello @Tangshitao ! As I understood, under the link is an implementation for deepBSD architecture, but not for DSM which is introduced in your paper. Could you provide a link to an implementation of DSM if there's exists one?
