### ISSUE TITLE
How to open the video files? 

### ISSUE THREAD

**Issue by hermit0** [Tangshitao/ClipShots#3]
Hi, I am wondering how to open the video files provided in the baidu pan, as these files have no specific type. Could you provide me  with the necessary information？ Thanks!!

**Comment by Tangshitao** [comment]
Sorry for late response. Please rename ClipShots to data.tar.gz.

**Comment by hermit0** [comment]
> Sorry for late response. Please rename ClipShots to data.tar.gz.

Thanks for your response.

**Comment by zhangshuaimm** [comment]
Have you opened the dataset? ''rename ClipShots to data.tar.gz''? I do not quite understand what it means.

**Comment by hermit0** [comment]
> Have you opened the dataset? ''rename ClipShots to data.tar.gz''? I do not quite understand what it means.
the uploaded dataset is compressed by the 'tar' command, and then splited into multiple files by the command 'split'。 so rename these files as 'data.tar.gz.a', 'data.tar.gz.b' , and then use the command 'cat' and ‘tar’ to uncompress the archives

**Comment by zhangshuaimm** [comment]
I have downloaded 'Clipshot-a' part , and renamed it as 'data.tar.gz.a'.I tried to use 'tar zxvf data.tar.gz.a' command. Howerver the error was shown to me that it is not in gzip format. Would you please tell me what was wrong with it,Thanks a lot.

**Comment by hermit0** [comment]
You should download all the files, and the 'cat' them into one file, and then uncompress them

At 2019-03-15 09:27:30, "zhangshuaimm" <notifications@github.com> wrote:


I have downloaded 'Clipshot-a' part , and renamed it as 'data.tar.gz.a'.I tried to use 'tar zxvf data.tar.gz.a' command. Howerver the error was shown to me that it is not in gzip format. Would you please tell me what was wrong with it,Thanks a lot.

**Comment by algoboy101** [comment]
* firstly, download from baidu pan.
* secondly，unzip it with 
```shell
cd ClipShots
# merge splited files, and unzip it.
cat ClipShots-a ClipShots-b ClipShots-c | tar -zx
```
