### ISSUE TITLE
Link for Data in English

### ISSUE THREAD

**Issue by TouqeerAhmad** [Tangshitao/ClipShots#5]
Hi, I am interested in using your data for my research project but unable to properly download the data set from the kink you have provide. I can not read Chinese and on downloading the clipShots, it downloads a .dmg file with Chinese language. 

Would you please share the data on a platform with English language. 

Thanks!

**Comment by Tangshitao** [comment]
I tried google drive, but the storage size is limited. I am working on this now. Please e-mail shitaot@gmail.com for a quick respond next time.

**Comment by Tangshitao** [comment]
Please use this link. https://storage.googleapis.com/clipshots/data.tar.gz
