### ISSUE TITLE
> Have you opened the dataset? ''rename ClipShots to data.tar.gz''? I do not quite understand what it means.

### ISSUE THREAD

**Issue by zhangshuaimm** [Tangshitao/ClipShots#7]
> Have you opened the dataset? ''rename ClipShots to data.tar.gz''? I do not quite understand what it means.
the uploaded dataset is compressed by the 'tar' command, and then splited into multiple files by the command 'split'。 so rename these files as 'data.tar.gz.a', 'data.tar.gz.b' , and then use the command 'cat' and ‘tar’ to uncompress the archives

_Originally posted by @hermit0 in https://github.com/Tangshitao/ClipShots/issues/3#issuecomment-473117445_

**Comment by Tangshitao** [comment]
No. Please rename the root directory.

**Comment by DYF-AI** [comment]
> No. Please rename the root directory.

The file name was changed to data.tar.gz, then what? It is still a folder. . .
