### ISSUE TITLE
The transitions contained in 'test.json' is inconsistent with the number mentioned in the paper

### ISSUE THREAD

**Issue by hermit0** [Tangshitao/ClipShots#8]
The transitions contained in 'test.json' is inconsistent with the number mentioned in the paper. In 'test.json', there is 4905 cut transitions and 2301 gradual transitions. But you mentitioned in the paper that the evaluation set consists of 5876 cut transitions and 2422 gradual transitions. Is there any problem?

**Comment by Tangshitao** [comment]
I may write the wrong number in the paper, please refer to the dataset I release here
